### ISSUE TITLE
connection closing before write

### ISSUE THREAD

**Issue by rthirumulu** [datamill-co/target-redshift#33] opened 2019-09-10 17:19 UTC
Currently using `tap-facebook` from singer.io to read from facebook marketing api and writing to Redshift using the `target-redshift` package. The connection establishes with Redshift and reads the data, but before i get to the write step I'm getting the error:

```py
Traceback (most recent call last):
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/target_postgres/postgres.py", line 129, in write_batch
    cur.execute('BEGIN;')
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/target_postgres/postgres.py", line 53, in execute
    return super(_MillisLoggingCursor, self).execute(query, vars)
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/psycopg2/extras.py", line 440, in execute
    return super(LoggingCursor, self).execute(query, vars)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/target_redshift/__init__.py", line 48, in main
    target_tools.main(redshift_target)
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/target_postgres/target_tools.py", line 25, in main
    stream_to_target(input_stream, target, config=config)
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/target_postgres/target_tools.py", line 69, in stream_to_target
    raise e
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/target_postgres/target_tools.py", line 63, in stream_to_target
    _flush_streams(streams, target, force=True)
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/target_postgres/target_tools.py", line 88, in _flush_streams
    _flush_stream(target, stream_buffer)
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/target_postgres/target_tools.py", line 81, in _flush_stream
    target.write_batch(stream_buffer)
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/target_redshift/redshift.py", line 58, in write_batch
    return PostgresTarget.write_batch(self, nullable_stream_buffer)
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/target_postgres/postgres.py", line 192, in write_batch
    cur.execute('ROLLBACK;')
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/target_postgres/postgres.py", line 53, in execute
    return super(_MillisLoggingCursor, self).execute(query, vars)
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/psycopg2/extras.py", line 440, in execute
    return super(LoggingCursor, self).execute(query, vars)
psycopg2.InterfaceError: cursor already closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv--target-redshift/bin/target-redshift", line 10, in <module>
    sys.exit(cli())
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/target_redshift/__init__.py", line 54, in cli
    main(args.config)
  File "/singer.io/venv--target-redshift/lib/python3.7/site-packages/target_redshift/__init__.py", line 48, in main
    target_tools.main(redshift_target)
psycopg2.InterfaceError: connection already closed
```

**Comment by AlexanderMann** [comment] 2019-09-17 15:10
@rthirumulu looks like we don't have the ability to pass along SSL information currently. [`target-postgres`](https://github.com/datamill-co/target-postgres/blob/master/target_postgres/__init__.py#L12-L25) has the ability to pass along SSL information to allow `psycopg2` to deal with certs and whatnot.

I think we've avoided doing this for `target-redshift` because we assumed most folks would be using an ssh bastion to connect to their Redshift instance.

If you can provide guidance on what values are needed to get [PsycoPG2 to connect to Redshift with SSL support](https://stackoverflow.com/questions/37584629/ssl-connection-to-redshift-using-psycopg2) (if that is indeed the issue you're facing) we'd be happy to get that baked into `target-redshift`.

Do you have any other projects connecting to this Redshift instance via python?

**Comment by AlexanderMann** [comment] 2019-09-30 13:49
@rthirumulu we're looking to wrap up features/whatnot for a release this week. Any updates on the above?

**Comment by awm33** [comment] 2020-05-16 21:10
We never quite identified this as a reproducible issue with the target, so I'm closing this out.

**Closed by awm33** 2020-05-16 21:10 UTC
